# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ui-chatbot-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      name: flask-ui-chatbot-tmpl
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: flask:ui-chatbot
          ports:
            - containerPort: 5000